name: login_flutter_app
description: A new Flutter project.



publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.17
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

#flutter_native_splash:
#  color: "f7f6f1"
#  color_dark: "#272727"
#  image: assets/





flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/dashboard/
    - assets/logo/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
